import { messages as enMessages } from '@/locales/en/messages';
import { messages as huMessages } from '@/locales/hu/messages';
import type { Locale } from './routing';

/**
 * Compiled Lingui catalogs, keyed by locale. Generated by `npm run
 * i18n:compile` from locales/<locale>/messages.po; untranslated entries were
 * already replaced with the English text at compile time (fallbackLocales), so
 * a catalog always covers the full ID set.
 */
export const catalogs: Record<Locale, Record<string, unknown>> = {
  en: enMessages,
  hu: huMessages,
};

export function catalogFor(locale: string): Record<string, unknown> {
  return catalogs[(locale in catalogs ? locale : 'en') as Locale];
}
